name: C/C++ CI on Mac OS X

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
    - build/*
  pull_request:
    branches:
    - master
    - build/*
  schedule:
  - cron: 0 2 * * 1-5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.config }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        config: [release]
        os: [macos-latest]    
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Build
      run: tools/build.sh ${{ matrix.config }}

    - name: Test
      run: ./tools/run-tests-all.sh
